name: final_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^6.1.1
  intl: ^0.18.1
  exif: ^3.3.0
  http: ^1.1.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  amplify_api: ^1.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  go_router: ^7.0.0
  image_picker: ^0.8.0
  path: ^1.8.3
  riverpod_annotation: ^2.0.1
  uuid: ^3.0.7
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  amplify_lints: ^3.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true
